---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-role-numad-centos7
    image: centos/systemd:latest
    privileged: true
    command: /usr/sbin/init
  - name: ansible-role-numad-centos6
    image: centos:6
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
